import "./globals.css";
import { Hind } from "next/font/google";

const hind = Hind({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Cool Typewriter | Marketing Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={hind.className}>
      <body className="m-8 flex flex-col">{children}</body>
    </html>
  );
}
