import "./globals.css";
import { Phudu } from "next/font/google";

const phudu = Phudu({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Cool Typewriter | Marketing Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={phudu.className}>
      <body className="m-8 flex flex-col">{children}</body>
    </html>
  );
}
